name: lint-check

on:
  pull_request:
    branches: [main, test, test-**]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: lint-check-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        uses: Maindarker/react-tsx-cli@master
        with:
          script: |
            pnpm install --no-frozen-lockfile

      - name: Lint changed files (PR)
        uses: Maindarker/react-tsx-cli@master
        with:
          script: |
            pnpm -s exec lint-staged \
              --config lint-staged.config.mjs \
              --diff ${{ github.event.pull_request.base.sha }} \
              --diff-filter=ACMRT \
              --allow-empty
